services:
    wg_admin.listener.questionnaire:
        class: ZCEPracticeTest\FrontBundle\Listener\QuestionListener
        arguments:
            #- @doctrine.orm.entity_manager
        tags:
            - { name: kernel.event_listener, event: event.zce.questions.init, method: onQuestionsInit }
