SimpleUser\User:
    type: mappedSuperclass
    fields:
        email:
            type: string
            length: 100
            nullable: false
        password:
            type: string
            length: 255
            nullable: true
        salt:
            type: string
            length: 255
            nullable: false
        roles:
            type: simple_array
            nullable: true
        name:
            type: string
            length: 255
            nullable: false
        timeCreated:
            column: time_created
            type: integer
            nullable: false
        username:
            type: string
            length: 100
            unique: true
            nullable: true
        isEnabled:
            type: boolean
            nullable: false
        confirmationToken:
            type: string
            length: 100
            nullable: true
        timePasswordResetRequested:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
