ZCEPracticeTest\Core\Entity\UserCustomFields:
    type: entity
    table: zce_user_custom_fields
    id:
        userId:
            type: integer
            unique: false
            nullable: false
            column: user_id
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
