ZCEPracticeTest\Core\Entity\User:
    type: entity
    table: user
    repositoryClass: ZCEPracticeTest\Core\Repository\UserRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            scale: 0
            length: 63
            unique: false
            nullable: false
            precision: 0
            column: first_name
        lastName:
            type: string
            scale: 0
            length: 63
            unique: false
            nullable: true
            precision: 0
            column: last_name
        email:
            type: string
            scale: 0
            length: 127
            unique: false
            nullable: true
            precision: 0
    lifecycleCallbacks: {  }
