ZCEPracticeTest\Core\Entity\AnswerQCMChoice:
    type: entity
    table: zce_answer_qcm_choice
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields: []
    manyToOne:
        answer:
            targetEntity: ZCEPracticeTest\Core\Entity\Answer
            cascade: {  }
            inversedBy: answerQCMChoices
            orphanRemoval: false
        questionQCMChoice:
            targetEntity: ZCEPracticeTest\Core\Entity\QuestionQCMChoice
            cascade: {  }
            orphanRemoval: false
    lifecycleCallbacks: {  }
