ZCEPracticeTest\Core\Entity\Question:
    type: mappedSuperclass
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entitled:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        code:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        category:
            targetEntity: ZCEPracticeTest\Core\Entity\Category
            cascade: {  }
            inversedBy: questions
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
