ZCEPracticeTest\Core\Entity\Question:
    type: entity
    table: zce_question
    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: integer
    discriminatorMap:
        0: Question
        1: QuestionQCM
        2: QuestionFree
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entitled:
            type: text
            length: 511
            nullable: false
        code:
            type: text
            length: 511
            nullable: true
    manyToOne:
        category:
            targetEntity: ZCEPracticeTest\Core\Entity\Category
            cascade: {  }
            inversedBy: questions
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
