ZCEPracticeTest\Core\Entity\Question:
    type: entity
    table: zce_question
    repositoryClass: ZCEPracticeTest\Core\Repository\QuestionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        type:
            type: integer
        entitled:
            type: string
            length: 511
        code:
            type: string
            length: 511
            nullable: true
        freeAnswer:
            type: string
            length: 255
            nullable: true
        nbAnswers:
            type: integer
            nullable: true
    oneToMany:
        questionQCMChoices:
            targetEntity: ZCEPracticeTest\Core\Entity\QuestionQCMChoice
            cascade:
                - remove
                - persist
            mappedBy: question
            orphanRemoval: false
            orderBy: null
    manyToOne:
        topic:
            targetEntity: ZCEPracticeTest\Core\Entity\Topic
            cascade: {  }
            inversedBy: questions
            joinColumns:
                topic_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
