ZCEPracticeTest\Core\Entity\Topic:
    type: entity
    table: zce_topic
    repositoryClass: ZCEPracticeTest\Core\Repository\TopicRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entitled:
            type: string
            length: 255
        isPrimary:
            type: boolean
    oneToMany:
        questions:
            targetEntity: ZCEPracticeTest\Core\Entity\Question
            cascade: {  }
            mappedBy: topic
            orphanRemoval: false
    lifecycleCallbacks: {  }
