ZCEPracticeTest\Core\Entity\QuestionQCMChoice:
    type: entity
    table: zce_question_qcm_choice
    repositoryClass: ZCEPracticeTest\Core\Repository\QuestionQCMChoiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entitled:
            type: string
            length: 255
        isValid:
            type: boolean
    manyToOne:
        question:
            targetEntity: ZCEPracticeTest\Core\Entity\Question
            cascade: {  }
            inversedBy: questionQCMChoices
            joinColumns:
                question_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
