ZCEPracticeTest\Core\Entity\Session:
    type: entity
    table: zce_session
    repositoryClass: ZCEPracticeTest\Core\Repository\SessionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        success:
            type: boolean
            nullable: true
        dateStart:
            type: datetime
            nullable: true
        dateFinished:
            type: datetime
            nullable: true
        nbTopicsValidated:
            type: integer
            nullable: true
    manyToOne:
        user:
            targetEntity: ZCEPracticeTest\Core\Entity\User
            cascade: {  }
            inversedBy: sessions
            orphanRemoval: false
        quiz:
            targetEntity: ZCEPracticeTest\Core\Entity\Quiz
            cascade: {  }
            inversedBy: sessions
            orphanRemoval: false
    oneToMany:
        answers:
            targetEntity: ZCEPracticeTest\Core\Entity\Answer
            mappedBy: session
            cascade:
                - remove
                - persist
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
