ZCEPracticeTest\Core\Entity\Quiz:
    type: entity
    table: zce_quiz
    repositoryClass: ZCEPracticeTest\Core\Repository\QuizRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 63
            nullable: true
    oneToMany:
        quizQuestions:
            targetEntity: ZCEPracticeTest\Core\Entity\QuizQuestion
            cascade:
                - all
            mappedBy: quiz
            orphanRemoval: false
            orderBy: null
        sessions:
            targetEntity: ZCEPracticeTest\Core\Entity\Session
            cascade: { }
            mappedBy: quiz
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
