ZCEPracticeTest\Core\Entity\QuestionQCMChoice:
    type: entity
    table: zce_question_qcm_choice
    repositoryClass: ZCEPracticeTest\Core\Repository\QuestionQCMChoiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entitled:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        isValid:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
    manyToOne:
        question:
            targetEntity: ZCEPracticeTest\Core\Entity\QuestionQCM
            cascade: {  }
            inversedBy: questionQCMChoices
            joinColumns:
                question_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
