ZCEPracticeTest\Core\Entity\User:
    type: entity
    table: zce_user
    repositoryClass: ZCEPracticeTest\Core\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            length: 63
            nullable: true
            column: first_name
        lastName:
            type: string
            length: 63
            nullable: true
            column: last_name
    oneToMany:
        sessions:
            targetEntity: ZCEPracticeTest\Core\Entity\Session
            cascade: { }
            mappedBy: user
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
