ZCEPracticeTest\Core\Entity\Category:
    type: entity
    table: zce_category
    repositoryClass: ZCEPracticeTest\Core\Repository\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        entitled:
            type: string
            length: 255
    oneToMany:
        questions:
            targetEntity: ZCEPracticeTest\Core\Entity\Question
            cascade: {  }
            mappedBy: category
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
