ZCEPracticeTest\Core\Entity\Answer:
    type: entity
    table: zce_answer
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        freeAnswer:
            type: string
            length: 255
            nullable: true
        tagged:
            type: boolean
        dateCreated:
            type: datetime
    manyToOne:
        question:
            targetEntity: ZCEPracticeTest\Core\Entity\Question
            cascade: {  }
            joinColumns:
                topic_id:
                    referencedColumnName: id
            orphanRemoval: false
        session:
            targetEntity: ZCEPracticeTest\Core\Entity\Session
            cascade: {  }
            inversedBy: answers
            joinColumns:
                topic_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        answerQCMChoices:
            targetEntity: ZCEPracticeTest\Core\Entity\AnswerQCMChoice
            mappedBy: answer
            orphanRemoval: false
            orderBy: null
    lifecycleCallbacks: {  }
