security:
    firewalls:
        login:
            pattern: ^/login$
        secured_area:
            pattern: ^.*$
            anonymous: true
            remember_me: []
            form:
                login_path: /login
                check_path: /login_check
            logout:
                logout_path: /logout

simple.user:
    userClass: ZCEPracticeTest\Core\Entity\User
    userTableName: zce_user
    userCustomFieldsTableName: zce_user_custom_fields
    templates:
        layout: @views/User/layout.html.twig
