security:
    firewalls:
        login:
            pattern: ^/user/login$
        secured_area:
            pattern: ^.*$
            anonymous: true
            remember_me: []
            form:
                login_path: /user/login
                check_path: /user/login_check
            logout:
                logout_path: /user/logout

simple.user:
    userClass: ZCEPracticeTest\Core\Entity\User
    userTableName: zce_user
    userCustomFieldsTableName: zce_user_custom_fields

swiftmailer: ~
