<?php

/**
 * PHP version 5
 *
 * @category Repository
 * @package  Core
 * @author   Maxence Perrin <mperrin@darkmira.fr>
 * @license  Darkmira <darkmira@darkmira.fr>
 * @link     www.darkmira.fr
 */
namespace ZCEPracticeTest\Core\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category Repository
 * @package  Core
 * @author   Maxence Perrin <mperrin@darkmira.fr>
 * @license  Darkmira <darkmira@darkmira.fr>
 * @link     www.darkmira.fr
 */
class SessionRepository extends EntityRepository
{
    /**
     * Get a fully loaded session (with relations)
     * 
     * @param integer $sessionId
     * @param integer $userId
     * 
     * @return \ZCEPracticeTest\Core\Entity\Session
     */
    public function getFullSession($sessionId, $userId)
    {
        $q = $this->createQueryBuilder('s')
            ->addSelect('u, q, a, quest, t, qc, ac')
            ->leftJoin('s.topicScores', 'ts')
            ->leftJoin('ts.topic', 'tst')
            ->leftJoin('s.user', 'u')
            ->leftJoin('s.quiz', 'q')
            ->leftJoin('s.answers', 'a')
            ->leftJoin('a.question', 'quest')
            ->leftJoin('quest.topic', 't')
            ->leftJoin('quest.questionQCMChoices', 'qc')
            ->leftJoin('a.answerQCMChoices', 'ac')
            ->where('s.id = :sessionId')
            ->andWhere('u.id = :userId')
            ->setParameters(array(
                ':sessionId' => $sessionId,
                ':userId' => $userId,
            ))
        ;
        
        return $q->getQuery()->getOneOrNullResult();
    }
}
